
import { Course, CourseLevel, User, UserRole, CodeSubmission, Review, SystemConfig, Assignment, PortfolioProject, StudyGroup, CourseStatus } from './types';

export const TRANSLATIONS = {
  en: {
    explore: "Explore Courses",
    myLearning: "My Learning",
    assignments: "Assignments",
    portfolio: "My Portfolio",
    studyGroups: "Study Groups",
    profile: "Profile",
    instructorPortal: "Instructor Portal",
    adminConsole: "Admin Console",
    logout: "Sign Out",
    login: "Login",
    register: "Register",
    createAccount: "Create Account",
    welcomeBack: "Welcome Back",
    accessJourney: "Access your learning journey",
    email: "Email Address",
    password: "Password",
    role: "Role",
    alreadyAccount: "Already have an account? Login",
    newUser: "New user? Create account",
    searchPlaceholder: "Search courses, docs, or ask AI...",
    dashboardTitle: "My Learning Dashboard",
    activeCourses: "Active Courses",
    lessonsCompleted: "Lessons Completed",
    studyTime: "Study Time",
    continue: "Continue",
    enroll: "Enroll Now",
    free: "Free",
    submit: "Submit",
    run: "Run Code",
    running: "Running...",
    submissionHistory: "Submission History",
    testCases: "Test Cases",
    passed: "Passed",
    failed: "Failed",
    projectSubmission: "Project Submission",
    repoUrl: "Git Repository URL",
    projectDesc: "Project Description",
    submitProject: "Submit Project",
    grades: "My Grades",
    course: "Course",
    assignment: "Assignment",
    score: "Score",
    feedback: "Feedback",
    status: "Status",
    pending: "Pending",
    graded: "Graded",
    nextStep: "Next Step",
    recommended: "Recommended",
    completeLesson: "Complete lesson",
    welcome: "Master Coding with AI-Powered Mentorship",
    welcomeDesc: "Interactive lessons, automated grading, and smart assistance.",
    changeLang: "Language",
    generalInfo: "General Information",
    settings: "Settings & Security",
    transactions: "Transaction History",
    messages: "Messages",
    inbox: "Inbox",
    reportIssue: "Report Issue",
    reviews: "Reviews",
    community: "Community",
    paymentMethod: "Payment Method",
    payNow: "Pay Now",
    writeReview: "Write a Review",
    leaveFeedback: "Leave Feedback",
    send: "Send",
    typeMessage: "Type a message...",
    selectIssueType: "Select Issue Type",
    describeIssue: "Describe the problem...",
    uiIssue: "Interface / UI",
    contentIssue: "Content / Exercise",
    paymentIssue: "Payment / Billing",
    otherIssue: "Other",
    reportSubmitted: "Report submitted successfully.",
    gateway: "Gateway",
    date: "Date",
    amount: "Amount",
    success: "Success",
    monthly: "Monthly",
    yearly: "Yearly",
    oneTime: "One-Time",
    reply: "Reply",
    cancel: "Cancel",
    selectContext: "Select Course Context (Optional)",
    userManagement: "User Management",
    courseManagement: "Course Management",
    learningPaths: "Learning Paths",
    searchUsers: "Search users by name or email...",
    resetPassword: "Reset Password",
    allRoles: "All Roles",
    filterByRole: "Filter by Role",
    approve: "Approve",
    archive: "Hide/Archive",
    publish: "Publish",
    restore: "Restore",
    moveTo: "Move to",
    levelBeginner: "Beginner Path",
    levelIntermediate: "Intermediate Path",
    levelAdvanced: "Advanced Path",
    passwordResetSent: "Password reset link sent to user.",
    courseUpdated: "Course status updated.",
    pathUpdated: "Learning path updated.",
    lockAccount: "Lock Account",
    unlockAccount: "Unlock Account",
    systemLogs: "System Logs",
    transactionManagement: "Transaction Management",
    systemSettings: "System Configuration",
    exportReport: "Export Report",
    filterTransactions: "Filter by User, Course...",
    generalConfig: "General Configuration",
    aiConfig: "AI Configuration",
    integrations: "Integrations",
    siteName: "Site Name",
    supportEmail: "Support Email",
    enableAI: "Enable AI Assistant",
    maxRequests: "Max Requests / User / Day",
    smtpServer: "SMTP Server",
    smsProvider: "SMS Provider",
    paymentGateways: "Payment Gateways",
    saveSettings: "Save Settings",
    configSaved: "System configuration saved successfully.",
    exporting: "Exporting report...",
    backupRestore: "Backup & Restore",
    reports: "Reports",
    createBackup: "Create Backup",
    backupCreated: "Backup created successfully.",
    restoring: "Restoring...",
    restoreSuccess: "System restored successfully.",
    confirmRestore: "Confirm Restore",
    restoreWarning: "Are you sure? Data since this backup will be lost.",
    fileName: "File Name",
    size: "Size",
    createdAt: "Created At",
    action: "Action",
    download: "Download",
    fullBackup: "Full System",
    dbBackup: "Database Only",
    filesBackup: "Files Only",
    statusNew: "New",
    statusResolved: "Resolved",
    replySent: "Reply sent successfully.",
    notifications: "Notifications",
    markRead: "Mark all as read",
    fullName: "Full Name",
    saveChanges: "Save Changes",
    bio: "Bio / About Me",
    changeAvatar: "Change Avatar",
    myCoursesTab: "My Courses",
    gradingTab: "Grading",
    detailsTab: "Details",
    curriculumTab: "Curriculum",
    liveClassesTab: "Live Classes",
    courseTitle: "Course Title",
    description: "Description",
    price: "Price",
    thumbnailUrl: "Thumbnail URL",
    saveClose: "Save & Close",
    addNewLesson: "Add New Lesson",
    lessonTitlePlaceholder: "Lesson Title...",
    video: "Video",
    reading: "Reading",
    coding: "Coding",
    project: "Project",
    contentPlaceholder: "Content URL, text, or instructions...",
    durationMin: "Duration (min)",
    addLessonBtn: "Add Lesson",
    scheduleSessionHeader: "Schedule Live Session",
    sessionTitlePlaceholder: "Class Title",
    meetLinkPlaceholder: "Google Meet Link",
    scheduleBtn: "Schedule",
    joinMeet: "Join Meet",
    noLiveSessions: "No live sessions scheduled.",
    liveTag: "LIVE",
    managedCourses: "Managed Courses",
    createCourseBtn: "Create Course",
    manageContent: "Manage Content",
    noCreatedCourses: "You haven't created any courses yet.",
    studentSubmission: "Student Submission",
    pendingReview: "Pending Review",
    aiAutoGrade: "AI Auto-Grade",
    scoreLabel: "Score (0-100)",
    feedbackLabel: "Feedback",
    skipBtn: "Skip",
    submitGradeBtn: "Submit Grade",
    selectSubmissionPrompt: "Select a submission from the list to grade.",
    allCaughtUp: "All caught up! No pending submissions.",
    uploadFile: "Upload File",
    writeCode: "Write Code",
    dragDropFile: "Drag & drop file here or click to select",
    submitWork: "Submit Work",
    submissionSuccess: "Submission received!",
    instructions: "Instructions",
    submitted: "Submitted",
    addCustomSubmission: "Add Submission",
    uploadAndSubmit: "Upload & Submit",
    selectEnrolledCourse: "Select Enrolled Course",
    selectCourseDefault: "Select Course",
    submissionTitle: "Assignment Title",
    addProject: "Add Project",
    projectTitle: "Project Title",
    tags: "Tags (comma separated)",
    create: "Create",
    enterGroup: "Enter Group",
    joinGroup: "Join Group",
    members: "members",
    typeGroupMessage: "Type a message...",
    noMessagesYet: "No messages yet. Be the first to say hello!",
    courseNotFound: "Course not found.",
    lessonNotFound: "Lesson not found.",
    accessRestricted: "Access Restricted",
    pleaseLogin: "Please login to access this course.",
    courseLocked: "Course Locked",
    mustEnroll: "You must enroll in this course to view content.",
    securePayment: "Secure Payment",
    totalToPay: "Total to Pay",
    scanPay: "Scan QR Code with Banking App to Pay",
    iHavePaid: "I have completed payment",
    contactAdmin: "Contact Admin",
    adminSupport: "Admin Support",
    messageSent: "Message Sent!",
    guestHelpText: "Need help accessing your account? Send a message to the admin.",
    howHelp: "How can we help you?",
    sendMessage: "Send Message",
    startLearning: "Start Learning",
    smartNavPlaceholder: "Go to settings, open python course...",
    myCourses: "My Courses",
    noCoursesEnrolled: "You are not enrolled in any courses yet.",
    task: "Task",
    leaderboard: "Leaderboard",
    submissionUrl: "Submission URL / Repo Link",
    submitBtn: "Submit",
    previousLesson: "Previous",
    lessons: "Lessons",
    liveClass: "Live Class",
    supportInquiries: "Support Inquiries",
    guestUser: "Guest User",
    startConversation: "Select a conversation to start chatting",
    statusActive: "Active",
    statusLocked: "Locked",
    actions: "Actions",
    createUser: "Create User",
    newPassPlaceholder: "New Password",
    systemConfigLoaded: "System configuration loaded.",
    Beginner: "Beginner",
    Intermediate: "Intermediate",
    Advanced: "Advanced",
    errorLogin: "Invalid email or password",
    errorLocked: "Account is locked due to too many failed attempts",
    noAssignments: "No pending assignments found."
  },
  vn: {
    explore: "Khám phá",
    myLearning: "Học tập",
    assignments: "Bài tập",
    portfolio: "Hồ sơ dự án",
    studyGroups: "Nhóm học tập",
    profile: "Hồ sơ cá nhân",
    instructorPortal: "Cổng giảng viên",
    adminConsole: "Quản trị hệ thống",
    logout: "Đăng xuất",
    login: "Đăng nhập",
    register: "Đăng ký",
    createAccount: "Tạo tài khoản",
    welcomeBack: "Chào mừng trở lại",
    accessJourney: "Truy cập hành trình học tập của bạn",
    email: "Địa chỉ Email",
    password: "Mật khẩu",
    role: "Vai trò",
    alreadyAccount: "Đã có tài khoản? Đăng nhập",
    newUser: "Người dùng mới? Tạo tài khoản",
    searchPlaceholder: "Tìm khóa học, tài liệu, hỏi AI...",
    dashboardTitle: "Bảng điều khiển học tập",
    activeCourses: "Khóa học đang học",
    lessonsCompleted: "Bài học đã xong",
    studyTime: "Thời gian học",
    continue: "Tiếp tục học",
    enroll: "Ghi danh ngay",
    free: "Miễn phí",
    submit: "Nộp bài",
    run: "Chạy thử Code",
    running: "Đang chạy...",
    submissionHistory: "Lịch sử nộp bài",
    testCases: "Test Cases",
    passed: "Đạt",
    failed: "Thất bại",
    projectSubmission: "Nộp dự án",
    repoUrl: "Git Repository URL",
    projectDesc: "Mô tả dự án",
    submitProject: "Nộp dự án",
    grades: "Bảng điểm",
    course: "Khóa học",
    assignment: "Bài tập",
    score: "Điểm số",
    feedback: "Nhận xét",
    status: "Trạng thái",
    pending: "Chờ chấm",
    graded: "Đã chấm",
    nextStep: "Bước tiếp theo",
    recommended: "Đề xuất cho bạn",
    completeLesson: "Hoàn thành bài học",
    welcome: "Thành thạo lập trình cùng AI Mentorship",
    welcomeDesc: "Bài học tương tác, chấm điểm tự động và trợ lý thông minh.",
    changeLang: "Ngôn ngữ",
    generalInfo: "Thông tin chung",
    settings: "Cài đặt & Bảo mật",
    transactions: "Lịch sử giao dịch",
    messages: "Tin nhắn",
    inbox: "Hộp thư",
    reportIssue: "Báo lỗi",
    reviews: "Đánh giá",
    community: "Cộng đồng",
    paymentMethod: "Phương thức thanh toán",
    payNow: "Thanh toán ngay",
    writeReview: "Viết đánh giá",
    leaveFeedback: "Gửi phản hồi",
    send: "Gửi",
    typeMessage: "Nhập tin nhắn...",
    selectIssueType: "Chọn loại vấn đề",
    describeIssue: "Mô tả vấn đề...",
    uiIssue: "Giao diện / UI",
    contentIssue: "Nội dung / Bài tập",
    paymentIssue: "Thanh toán / Hóa đơn",
    otherIssue: "Khác",
    reportSubmitted: "Đã gửi báo cáo thành công.",
    gateway: "Cổng thanh toán",
    date: "Ngày",
    amount: "Số tiền",
    success: "Thành công",
    monthly: "Hàng tháng",
    yearly: "Hàng năm",
    oneTime: "Một lần",
    reply: "Trả lời",
    cancel: "Hủy bỏ",
    selectContext: "Chọn ngữ cảnh khóa học (Tùy chọn)",
    userManagement: "Quản lý người dùng",
    courseManagement: "Quản lý khóa học",
    learningPaths: "Lộ trình học tập",
    searchUsers: "Tìm kiếm người dùng...",
    resetPassword: "Đặt lại mật khẩu",
    allRoles: "Tất cả vai trò",
    filterByRole: "Lọc theo vai trò",
    approve: "Phê duyệt",
    archive: "Ẩn / Lưu trữ",
    publish: "Xuất bản",
    restore: "Khôi phục",
    moveTo: "Chuyển sang",
    levelBeginner: "Lộ trình Cơ bản",
    levelIntermediate: "Lộ trình Trung cấp",
    levelAdvanced: "Lộ trình Nâng cao",
    passwordResetSent: "Đã gửi link đặt lại mật khẩu.",
    courseUpdated: "Đã cập nhật trạng thái khóa học.",
    pathUpdated: "Đã cập nhật lộ trình học.",
    lockAccount: "Khóa tài khoản",
    unlockAccount: "Mở khóa",
    systemLogs: "Nhật ký hệ thống",
    transactionManagement: "Quản lý giao dịch",
    systemSettings: "Cấu hình hệ thống",
    exportReport: "Xuất báo cáo",
    filterTransactions: "Lọc theo User, Khóa học...",
    generalConfig: "Cấu hình chung",
    aiConfig: "Cấu hình AI",
    integrations: "Tích hợp",
    siteName: "Tên trang web",
    supportEmail: "Email hỗ trợ",
    enableAI: "Bật trợ lý AI",
    maxRequests: "Giới hạn Request / User / Ngày",
    smtpServer: "Máy chủ SMTP",
    smsProvider: "Nhà cung cấp SMS",
    paymentGateways: "Cổng thanh toán",
    saveSettings: "Lưu cài đặt",
    configSaved: "Đã lưu cấu hình hệ thống.",
    exporting: "Đang xuất báo cáo...",
    backupRestore: "Sao lưu & Khôi phục",
    reports: "Báo cáo & Hỗ trợ",
    createBackup: "Tạo bản sao lưu",
    backupCreated: "Đã tạo bản sao lưu thành công.",
    restoring: "Đang khôi phục...",
    restoreSuccess: "Khôi phục hệ thống thành công.",
    confirmRestore: "Xác nhận khôi phục",
    restoreWarning: "Bạn có chắc chắn? Dữ liệu mới sau bản sao lưu này sẽ bị mất.",
    fileName: "Tên tệp",
    size: "Kích thước",
    createdAt: "Ngày tạo",
    action: "Hành động",
    download: "Tải xuống",
    fullBackup: "Toàn bộ hệ thống",
    dbBackup: "Chỉ cơ sở dữ liệu",
    filesBackup: "Chỉ tệp tin",
    statusNew: "Mới",
    statusResolved: "Đã giải quyết",
    replySent: "Đã gửi trả lời thành công.",
    notifications: "Thông báo",
    markRead: "Đánh dấu tất cả đã đọc",
    fullName: "Họ và tên",
    saveChanges: "Lưu thay đổi",
    bio: "Giới thiệu bản thân",
    changeAvatar: "Đổi ảnh đại diện",
    myCoursesTab: "Khóa học của tôi",
    gradingTab: "Chấm điểm",
    detailsTab: "Chi tiết",
    curriculumTab: "Giáo trình",
    liveClassesTab: "Lớp học trực tuyến",
    courseTitle: "Tên khóa học",
    description: "Mô tả",
    price: "Giá tiền",
    thumbnailUrl: "Link ảnh bìa",
    saveClose: "Lưu & Đóng",
    addNewLesson: "Thêm bài học mới",
    lessonTitlePlaceholder: "Tiêu đề bài học...",
    video: "Video",
    reading: "Bài đọc",
    coding: "Lập trình",
    project: "Dự án",
    contentPlaceholder: "URL, nội dung hoặc hướng dẫn...",
    durationMin: "Thời lượng (phút)",
    addLessonBtn: "Thêm bài học",
    scheduleSessionHeader: "Lên lịch lớp học trực tuyến",
    sessionTitlePlaceholder: "Tiêu đề lớp học",
    meetLinkPlaceholder: "Link Google Meet",
    scheduleBtn: "Lên lịch",
    joinMeet: "Tham gia Meet",
    noLiveSessions: "Chưa có lịch học trực tuyến.",
    liveTag: "TRỰC TUYẾN",
    managedCourses: "Quản lý khóa học",
    createCourseBtn: "Tạo khóa học",
    manageContent: "Quản lý nội dung",
    noCreatedCourses: "Bạn chưa tạo khóa học nào.",
    studentSubmission: "Bài nộp của sinh viên",
    pendingReview: "Chờ xem xét",
    aiAutoGrade: "AI Chấm tự động",
    scoreLabel: "Điểm (0-100)",
    feedbackLabel: "Nhận xét",
    skipBtn: "Bỏ qua",
    submitGradeBtn: "Gửi kết quả",
    selectSubmissionPrompt: "Chọn một bài nộp từ danh sách để chấm.",
    allCaughtUp: "Đã xong hết! Không còn bài tập cần chấm.",
    uploadFile: "Tải tệp lên",
    writeCode: "Viết Code",
    dragDropFile: "Kéo thả tệp hoặc bấm để chọn",
    submitWork: "Nộp bài làm",
    submissionSuccess: "Đã nhận bài nộp!",
    instructions: "Hướng dẫn",
    submitted: "Đã nộp",
    addCustomSubmission: "Nộp bài mới",
    uploadAndSubmit: "Tải lên & Nộp",
    selectEnrolledCourse: "Chọn khóa học",
    selectCourseDefault: "Chọn khóa học",
    submissionTitle: "Tiêu đề bài tập",
    addProject: "Thêm dự án",
    projectTitle: "Tên dự án",
    tags: "Thẻ (cách nhau bởi dấu phẩy)",
    create: "Tạo mới",
    enterGroup: "Vào nhóm",
    joinGroup: "Tham gia nhóm",
    members: "thành viên",
    typeGroupMessage: "Nhập tin nhắn...",
    noMessagesYet: "Chưa có tin nhắn. Hãy là người đầu tiên chào hỏi!",
    courseNotFound: "Không tìm thấy khóa học.",
    lessonNotFound: "Không tìm thấy bài học.",
    accessRestricted: "Truy cập bị hạn chế",
    pleaseLogin: "Vui lòng đăng nhập để truy cập khóa học này.",
    courseLocked: "Khóa học bị khóa",
    mustEnroll: "Bạn phải ghi danh khóa học này để xem nội dung.",
    securePayment: "Thanh toán an toàn",
    totalToPay: "Tổng thanh toán",
    scanPay: "Quét mã QR bằng App Ngân hàng để thanh toán",
    iHavePaid: "Tôi đã thanh toán",
    contactAdmin: "Liên hệ Admin",
    adminSupport: "Hỗ trợ Admin",
    messageSent: "Tin nhắn đã gửi!",
    guestHelpText: "Cần trợ giúp truy cập? Gửi tin nhắn cho quản trị viên.",
    howHelp: "Chúng tôi có thể giúp gì cho bạn?",
    sendMessage: "Gửi tin nhắn",
    startLearning: "Bắt đầu học ngay",
    smartNavPlaceholder: "Đi tới cài đặt, mở khóa học python...",
    myCourses: "Khóa học của tôi",
    noCoursesEnrolled: "Bạn chưa ghi danh khóa học nào.",
    task: "Bài tập",
    leaderboard: "Bảng xếp hạng",
    submissionUrl: "Link bài làm / Repo",
    submitBtn: "Nộp bài",
    previousLesson: "Bài trước",
    lessons: "Bài học",
    liveClass: "Lịch học Online",
    supportInquiries: "Yêu cầu hỗ trợ",
    guestUser: "Khách",
    startConversation: "Chọn một cuộc hội thoại để bắt đầu chat",
    statusActive: "Hoạt động",
    statusLocked: "Bị khóa",
    actions: "Hành động",
    createUser: "Thêm người dùng",
    newPassPlaceholder: "Mật khẩu mới",
    systemConfigLoaded: "Đã tải cấu hình hệ thống.",
    Beginner: "Cơ bản",
    Intermediate: "Trung cấp",
    Advanced: "Nâng cao",
    errorLogin: "Email hoặc mật khẩu không đúng",
    errorLocked: "Tài khoản bị khóa do đăng nhập sai quá nhiều lần",
    noAssignments: "Không có bài tập nào."
  }
};

export const DEFAULT_SYSTEM_CONFIG: SystemConfig = {
  siteName: "EduCode.AI",
  supportEmail: "support@educode.ai",
  aiEnabled: true,
  aiRequestLimit: 50,
  smtpHost: "smtp.educode.ai",
  smsProvider: "Twilio",
  paymentGateways: {
    vnpay: true,
    momo: true,
    stripe: false
  }
};

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Nguyễn Viết Hoàng',
    email: 'hoangnguyennn2206@gmail.com',
    password: '22062005',
    role: UserRole.ADMIN,
    status: 'active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Nguyen+Viet+Hoang&background=0D8ABC&color=fff',
    coursesEnrolled: [],
    preferences: { language: 'vn', notifications: true }
  },
  {
    id: 'u2',
    name: 'Teacher One',
    email: 'teacher@edu.co',
    password: 'password',
    role: UserRole.TEACHER,
    status: 'active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Teacher+One&background=random',
    coursesEnrolled: [],
    preferences: { language: 'en', notifications: true }
  },
  {
    id: 'u3',
    name: 'Student One',
    email: 'student@edu.co',
    password: 'password',
    role: UserRole.STUDENT,
    status: 'active',
    avatarUrl: 'https://ui-avatars.com/api/?name=Student+One&background=random',
    coursesEnrolled: ['c1'],
    preferences: { language: 'en', notifications: true }
  }
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Python for Beginners',
    description: 'Learn Python from scratch. Master variables, loops, and functions.',
    instructor: 'Teacher One',
    instructorId: 'u2',
    thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    price: 49.99,
    level: CourseLevel.BEGINNER,
    language: 'Python',
    rating: 4.8,
    studentsCount: 120,
    status: 'published',
    progress: 45,
    tags: ['Python', 'Coding'],
    lessons: [
       { id: 'l1', title: 'Introduction to Python', type: 'video', content: 'https://www.youtube.com/embed/_uQrJ0TkZlc', durationMinutes: 10, completed: true },
       { id: 'l2', title: 'Variables and Types', type: 'reading', content: '# Python Variables\nVariables are containers for storing data values.', durationMinutes: 15, completed: true },
       { id: 'l3', title: 'First Script', type: 'coding', content: 'print("Hello World")', durationMinutes: 20, completed: false }
    ],
    reviews: [],
    liveSessions: []
  },
  {
    id: 'c2',
    title: 'Advanced React Patterns',
    description: 'Deep dive into hooks, context, and performance optimization.',
    instructor: 'Teacher One',
    instructorId: 'u2',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    price: 89.99,
    level: CourseLevel.ADVANCED,
    language: 'JavaScript',
    rating: 4.9,
    studentsCount: 85,
    status: 'published',
    progress: 0,
    tags: ['React', 'Frontend'],
    lessons: [],
    reviews: [],
    liveSessions: []
  },
  {
    id: 'c3',
    title: 'Java Fundamentals',
    description: 'Master Object Oriented Programming with Java.',
    instructor: 'Teacher One',
    instructorId: 'u2',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    price: 0,
    level: CourseLevel.BEGINNER,
    language: 'Java',
    rating: 4.7,
    studentsCount: 200,
    status: 'published',
    progress: 0,
    tags: ['Java', 'Backend'],
    lessons: [
      { id: 'l_java_1', title: 'Setup Java', type: 'reading', content: 'Install JDK and IntelliJ IDEA', durationMinutes: 15, completed: false },
      { id: 'l_java_2', title: 'Hello Java', type: 'coding', content: 'public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello");\n  }\n}', durationMinutes: 20, completed: false }
    ],
    reviews: [],
    liveSessions: []
  },
  {
    id: 'c4',
    title: 'Web Design Basics',
    description: 'HTML5, CSS3 and Responsive Design principles.',
    instructor: 'Teacher One',
    instructorId: 'u2',
    thumbnail: 'https://images.unsplash.com/photo-1547658719-da2b51169166?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    price: 0,
    level: CourseLevel.BEGINNER,
    language: 'HTML/CSS',
    rating: 4.6,
    studentsCount: 300,
    status: 'published',
    progress: 0,
    tags: ['Web', 'Design'],
    lessons: [],
    reviews: [],
    liveSessions: []
  }
];

export const MOCK_SUBMISSIONS: CodeSubmission[] = [
  {
    id: 's1',
    studentId: 'u3',
    studentName: 'Student One',
    courseId: 'c1',
    courseTitle: 'Python for Beginners',
    lessonId: 'l3',
    lessonTitle: 'First Script',
    type: 'coding',
    code: 'print("Hello World")',
    score: 100,
    feedback: 'Perfect!',
    submittedAt: '2023-10-26T10:00:00Z',
    status: 'graded'
  }
];

export const MOCK_ASSIGNMENTS: Assignment[] = [
    {
        id: 'a1',
        courseId: 'c1',
        courseTitle: 'Python for Beginners',
        title: 'Final Project',
        description: 'Build a calculator app',
        dueDate: '2023-12-31',
        status: 'open'
    }
];

export const MOCK_PROJECTS: PortfolioProject[] = [
    {
        id: 'p1',
        studentId: 'u3',
        title: 'Weather App',
        description: 'React based weather dashboard',
        imageUrl: 'https://picsum.photos/400/300',
        tags: ['React', 'API'],
        createdAt: Date.now()
    }
];

export const MOCK_GROUPS: StudyGroup[] = [
    {
        id: 'g1',
        name: 'Python Beginners',
        description: 'A group for those starting with Python.',
        members: ['u3', 'u2'],
        memberCount: 2,
        posts: []
    },
    {
      id: 'g2',
      name: 'AI & Python Community',
      description: 'Large community for AI enthusiasts. 50+ active members.',
      members: ['u3', 'u2', 'u1'], // Add mock users
      memberCount: 53,
      posts: [
        {
          id: 'gp1',
          userId: 'u2',
          userName: 'Teacher One',
          userAvatar: 'https://ui-avatars.com/api/?name=Teacher+One&background=random',
          content: 'Welcome everyone to the AI community!',
          createdAt: Date.now() - 10000000,
          replies: []
        }
      ]
    }
];
